### PR TITLE
Fix #645: NSBlockOperation does not execute

### LINKED ISSUE #645: NSBlockOperation does not execute when added to a NSOperationQueue
Using a release built from HEAD, an NSBlockOperation does not execute when added to a NSOperationQueue. 

This works as expected using the 1st July release.

Example code:
```
self.op = [NSBlockOperation blockOperationWithBlock:^{
    NSLog(@"DO SOMETHING");
}];
[self.queue addOperation:self.op];
```

The block is not executed and the log statement is not outputted.

### PR DESCRIPTION
**Pull request by jofre-ms**

### CODE REVIEW

**Comment by msft-Jeyaram** [comment]
> + (instancetype)blockOperationWithBlock:(void (^)())block {

handle NULL blocks?

---
Refers to: Frameworks/Foundation/NSBlockOperation.mm:41 in 7aa2642. [](commit_id = 7aa264259c75df49045a2e04458e7cf1d0871063, deletion_comment = False)

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by msft-Jeyaram** [comment]
:shipit:

**Comment by bbowman** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
In CI build.

**Comment by jofre-ms** [comment]
> + (instancetype)blockOperationWithBlock:(void (^)())block {

Current behavior for blockOperationWithBlock:NULL is crashing, which matches the reference platform.

---
In reply to: [232789363](https://github.com/Microsoft/WinObjC/pull/646#issuecomment-232789363) [](ancestors = 232789363)

---
Refers to: Frameworks/Foundation/NSBlockOperation.mm:41 in 7aa2642. [](commit_id = 7aa264259c75df49045a2e04458e7cf1d0871063, deletion_comment = False)

**Comment by jofre-ms** [comment]
thanks

---
In reply to: [232791899](https://github.com/Microsoft/WinObjC/pull/646#issuecomment-232791899) [](ancestors = 232791899)

**Pull request merged**
