### PR TITLE
It's completely ok to give nil as errorCode pointer (2nd try)...

### PR DESCRIPTION
**Pull request by mgoemmel**
...so we should be prepared for this.

### CODE REVIEW

**Comment by rajsesh-msft** [comment]
nitty comment to use {} with the if statements. 

if (outError) {
   *outError=nil;
}

**Comment by mgoemmel** [comment]
> nitty comment to use {} with the if statements. 

Fixed.

**Comment by rajsesh-msft** [comment]
Thanks again! One more step needed. You have to sign the CLA as mentioned here.  You have to do it only once for all MS open source projects.  

https://github.com/Microsoft/WinObjC/wiki/How-to-Contribute

**Comment by rajsesh-msft** [comment]
Thanks for your contribution.

**Pull request merged**
