### PR TITLE
Move #pragma statements so that they do not interfere with API annota…

### PR DESCRIPTION
**Pull request by asimonov-msft**
…tion block.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
@bbowman I fully agree, but I don't think that is worth rejecting this hotfix for. :smile:

**Comment by bbowman** [comment]
Can @asimonov-msft file an issue for this then?

**Comment by jaredhms** [comment]
:shipit:

**Comment by arjun-msft** [comment]
:shipit:

**Comment by asimonov-msft** [comment]
@bbowman @DHowett-MSFT Unfortunately, this is an issue with how libclang associates the doxygen-style comment blocks with entries in the AST. As a result, this is not something that we can easily fix.

**Pull request merged**
