### PR TITLE
Exporting the glMapBufferRangeEXT function (#1314)

### PR DESCRIPTION
**Pull request by sakrist**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1350)

### CODE REVIEW

**Comment by jaredhms** [comment]
:shipit:

**Comment by jaredhms** [comment]
Thanks for the contribution; it looks good, but please sign the CLA so we can accept the PR.

**Comment by jaredhms** [comment]
@rajsesh-msft

**Comment by sakrist** [comment]
@jaredhms done.

**Pull request merged**
