### PR TITLE
Infrastructure to support finite background tasks

### PR DESCRIPTION
**Pull request by mnithish**

### CODE REVIEW

**Comment by mnithish** [comment]
@jaredhms is added to the review. #Closed

**Comment by mnithish** [comment]
@rajsesh-msft is added to the review. #Closed

**Comment by mnithish** [comment]
@bbowman is added to the review. #Closed

**Comment by mnithish** [comment]
@aballway is added to the review. #Closed

**Comment by aballway** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
A more detailed description would be good to have (context on what is needed for building this, etc).  Can be updated when the PR is merged.

**Comment by rajsesh-msft** [comment]
:shipit:

**Comment by mnithish** [comment]
CI build passed

**Pull request merged**
