### PR TITLE
* Removed duplicate implementation of CGContextAddArc.

### LINKED ISSUE #630: CGContextAddArc is duplicated and stubbed version wins
/**
 @Status Interoperable
*/
void CGContextAddArc(CGContextRef ctx, float x, float y, float radius, float startAngle, float endAngle, bool clockwise) {
    ctx->Backing()->CGContextAddArc(x, y, radius, startAngle, endAngle, clockwise);
}

void CGContextAddArc(CGContextRef c, CGFloat x, CGFloat y, CGFloat radius, CGFloat startAngle, CGFloat endAngle, int clockwise) {
    UNIMPLEMENTED();
}

### PR DESCRIPTION
**Pull request by rajsesh-msft**
* Fixed params to take CGFloat instead of float for the public CGContext methods.
* Change CGCatalog to use points that will fit in screen.
* Fix CGContextAddArc to not draw the line - cairo will do it if needed.
* Fix CGContextFillPath() to not preserve path after fill.  This is
* required according to documentation (also matches reference platform
* behavior).

Fixes #630

### CODE REVIEW

**Comment by rajsesh-msft** [comment]
@MSFTFox is added to the review. #Closed

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT is added to the review. #Closed

**Comment by aballway** [comment]
:shipit:

**Comment by ms-jihua** [comment]
:shipit:

**Comment by msft-Jeyaram** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
```
* Fix CGContextFillPath() to not preserve path after fill.  This is
* required according to documentation (also matches reference platform
* behavior).
```

This will damage the WOCCatalog text shapes ("Text Display") example, since it has some CAShapeLayers that it fills and strokes without recreating the path.

**Comment by rajsesh-msft** [comment]
No, I don't see anything wrong there.  In fact, this method is not used elsewhere in woccatalog sample.  Do you mean something different?

---
In reply to: [249639757](https://github.com/Microsoft/WinObjC/pull/1034#issuecomment-249639757) [](ancestors = 249639757)

**Comment by rajsesh-msft** [comment]
Synced up offline, this seems like a bug in CAShapeLayer.

---
In reply to: [249642560](https://github.com/Microsoft/WinObjC/pull/1034#issuecomment-249642560) [](ancestors = 249642560,249639757)

**Comment by rajsesh-msft** [comment]
Also _UIGroupEdgeView

---
In reply to: [249644435](https://github.com/Microsoft/WinObjC/pull/1034#issuecomment-249644435) [](ancestors = 249644435,249642560,249639757)

**Comment by MSFTFox** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
:shipit:

**Pull request merged**
