### PR TITLE
Disable /WHOLEARCHIVE and reintroduce the force includes for now.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
We'll need to revert this change when `/WHOLEARCHIVE` works.

Ref. #878 
Ref. #874

### CODE REVIEW

**Comment by bbowman** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
@jaredhms @pradipd Ping; This is P0 for Monday.

**Comment by jaredhms** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
Thanks!

**Pull request merged**
