### PR TITLE
Remove extra CGDataProviderRelease calls in GLKit

### LINKED ISSUE #1736: SpriteSample is crashing on launch
SpriteSample is crashing on launch for all configurations (arm/win32 debug/release).

### PR DESCRIPTION
**Pull request by aballway**
Fixes #1736

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1741)

### CODE REVIEW

**Comment by jaredhms** [comment]
>         CGDataProviderRelease(provider);

what about this one?

---
Refers to: Frameworks/GLKit/GLKTexture.mm:449 in 8f54c08. [](commit_id = 8f54c0844a0643801435014a7f013ce872d944d1, deletion_comment = False)

**Comment by jaredhms** [comment]
>     CGDataProviderRelease(provider);

And this?

---
Refers to: Frameworks/GLKit/GLKTexture.mm:507 in 8f54c08. [](commit_id = 8f54c0844a0643801435014a7f013ce872d944d1, deletion_comment = False)

**Comment by jaredhms** [comment]
>     CGDataProviderRef provider = CGImageGetDataProvider(img);

May be worth adding comments to each of these calls to make it clear why we're intentionally not releasing providers returned from this API?

---
Refers to: Frameworks/GLKit/GLKTexture.mm:311 in 8f54c08. [](commit_id = 8f54c0844a0643801435014a7f013ce872d944d1, deletion_comment = False)

**Comment by ms-jihua** [comment]
>     provider = CGImageGetDataProvider(img);

eesh, how misleading

---
Refers to: Frameworks/GLKit/GLKTexture.mm:421 in 8f54c08. [](commit_id = 8f54c0844a0643801435014a7f013ce872d944d1, deletion_comment = False)

**Comment by aballway** [comment]
>     provider = CGImageGetDataProvider(img);

this makes me so sad :(

---
In reply to: [273932290](https://github.com/Microsoft/WinObjC/pull/1741#issuecomment-273932290) [](ancestors = 273932290)

---
Refers to: Frameworks/GLKit/GLKTexture.mm:421 in 8f54c08. [](commit_id = 8f54c0844a0643801435014a7f013ce872d944d1, deletion_comment = False)

**Comment by aballway** [comment]
>     CGDataProviderRef provider = CGImageGetDataProvider(img);

No, this follows the "Get Rule" of not taking ownership of the returned pointer so it's sort of documented in the name by way of convention.  If it were violating that convention the comments would be helpful, but I don't think they're necessary here.

---
In reply to: [273931892](https://github.com/Microsoft/WinObjC/pull/1741#issuecomment-273931892) [](ancestors = 273931892)

---
Refers to: Frameworks/GLKit/GLKTexture.mm:311 in 8f54c08. [](commit_id = 8f54c0844a0643801435014a7f013ce872d944d1, deletion_comment = False)

**Comment by DHowett-MSFT** [comment]
>     CGDataProviderRef provider = CGImageGetDataProvider(img);

@jaredhms it's a CF "Get" function, they should _never_ be released!

---
In reply to: [273931892](https://github.com/Microsoft/WinObjC/pull/1741#issuecomment-273931892) [](ancestors = 273931892)

---
Refers to: Frameworks/GLKit/GLKTexture.mm:311 in 8f54c08. [](commit_id = 8f54c0844a0643801435014a7f013ce872d944d1, deletion_comment = False)

**Comment by DHowett-MSFT** [comment]
>     CGDataProviderRef provider = CGImageGetDataProvider(img);

@aballway If you want to be _awesome_, you could make these woc::StrongCF and delete all the manual releases.

---
In reply to: [273935543](https://github.com/Microsoft/WinObjC/pull/1741#issuecomment-273935543) [](ancestors = 273935543,273931892)

---
Refers to: Frameworks/GLKit/GLKTexture.mm:311 in 8f54c08. [](commit_id = 8f54c0844a0643801435014a7f013ce872d944d1, deletion_comment = False)

**Comment by jaredhms** [comment]
:shipit:

**Pull request merged**
