### PR TITLE
Merge develop to CGD2D branch

### PR DESCRIPTION
**Pull request by rajsesh-msft**

### CODE REVIEW

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT is added to the review. #Closed

**Comment by rajsesh-msft** [comment]
@MSFTFox is added to the review. #Closed

**Comment by rajsesh-msft** [comment]
@msft-Jeyaram is added to the review. #Closed

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by msft-Jeyaram** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
technically i am merging CT-DW onto CGD2D.

**Comment by MSFTFox** [comment]
:shipit:

**Pull request merged**
