### PR TITLE
AddressBook Framework -- Design Doc

### PR DESCRIPTION
**Pull request by chadimoussi**
Added AddressBook design doc.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
I approve this message :shipit:

**Comment by DHowett-MSFT** [comment]
This may not require a CI build, since it's only in `docs/`?

**Comment by chadimoussi** [comment]
Already kicked them off (thanks to a handy script!), but I can cancel if they are not necessary

---
In reply to: [244238545](https://github.com/Microsoft/WinObjC/pull/952#issuecomment-244238545) [](ancestors = 244238545)

**Pull request merged**
