### PR TITLE
use more portable _countof alternative

### PR DESCRIPTION
**Pull request by bbowman**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1272)

### CODE REVIEW

**Comment by ms-jihua** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
I do love some good `std::extent<T>`.

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by msft-Jeyaram** [comment]
:shipit:

**Pull request merged**
