### PR TITLE
1712.1 release

### PR DESCRIPTION
**Pull request by MSFTFox**
Merge develop into master.

Updates:

* libdispatch was updated to support the `dispatch_queue_specific` APIs
* OSSpinLock and friends were made available
* Bundles will now load localized resources appropriate for the user's preferred languages

This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/2825)

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
nit: please rename this pull request
not a nit: please reword the entire body of the pull request before you merge it, it's riddled with curiosities.

**Comment by DHowett-MSFT** [comment]
(When Raj does develop -> master merges, he names the pull request after the release name, as in #2814.)

**Comment by MSFTFox** [comment]
Oh, I was following how he named the merge from master into develop earlier.

**Comment by DHowett-MSFT** [comment]
further nits:
* libdispatch was updated to _support_ the `dispatch_queue_specific` APIs
* OSSpinLock and friends were made available _(not OSSpingLock)_
* Bundles will now load localized resources appropriate for the user's preferred languages.

**Pull request merged**
