### PR TITLE
Revert "Adding support for ClearRect with clipping geometry"

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Reverts Microsoft/WinObjC#2053

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
The tests in this pull request were actually failing with #2027 merged.

**Comment by msft-Jeyaram** [comment]
uh I'll look into this.
Thanks dustin.

**Comment by DHowett-MSFT** [comment]
@rajsesh-msft if this passes the build, I'd like to merge it tonight. Thoughts?

**Comment by rajsesh-msft** [comment]
@DHowett-MSFT, yes please!

**Pull request merged**
