### PR TITLE
Upgrade forgotten ToolsVersion settings

### PR DESCRIPTION
**Pull request by memontic-ms**
More upgrade changes needed because:
1. A couple vsimported projects that went in after my initial pass through for upgrades
2. ToolsVersion="12.0" that missed my pass through

### CODE REVIEW

**Comment by jaredhms** [comment]
:shipit:

**Comment by pradipd** [comment]
Do you need to rerun vsimporter on these?

**Comment by pradipd** [comment]
nevermind.

---
In reply to: [289983668](https://github.com/Microsoft/WinObjC/pull/2343#issuecomment-289983668) [](ancestors = 289983668)

**Comment by pradipd** [comment]
:shipit:

**Pull request merged**
