### PR TITLE
February 2018 Release

### PR DESCRIPTION
**Pull request by MSFTFox**
Merge develop into master.

Updates:

- Adds support for Visual Studio 2017 Update 15.4.5
- Update projections to target the 10.0.16299 Windows SDK
- Address C++ compiler longevity issues

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/2845)

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
please remove `1802.1` from any commit names and titles immediately

we can't have gitversion freaking out again

**Comment by DHowett-MSFT** [comment]
I'm alarmed that there are two :x: in the commit history this merge covers.

**Comment by MSFTFox** [comment]
Not sure why those ❌'s are there. One particular build failed due to an issue recently fixed, but that shouldn't have affected these older commits.

**Comment by DHowett-MSFT** [comment]
I think that when you kick off the build for this, you have to set `PackageVersionOverride`. then afterwards merge and tag it

**Pull request merged**
