### PR TITLE
Add CFNetwork.dll to NuGet package

### PR DESCRIPTION
**Pull request by bviglietta**
CFNetwork.dll is now a required framework library, so I'm adding it to the NuGet package.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1341)

### CODE REVIEW

**Comment by bviglietta** [comment]
@bbowman is added to the review. #Closed

**Comment by bbowman** [comment]
:shipit:

**Comment by bbowman** [comment]
>     <version>1.0.0</version>

should be bumped no?

---
Refers to: build/nuget/WinObjC.nuspec:5 in 08bff3a. [](commit_id = 08bff3ab1f2933749080aab51a25cf7cf3b9e1c9, deletion_comment = False)

**Comment by bbowman** [comment]
:clock1:

**Comment by memontic-ms** [comment]
:shipit:

**Comment by bbowman** [comment]
>     <version>1.0.0</version>

Also thinking but we probably should be 0.0.X since we technically haven't released a first truly usable package. We are still in "beta"/development with these packages.

---
In reply to: [259294852](https://github.com/Microsoft/WinObjC/pull/1341#issuecomment-259294852) [](ancestors = 259294852)

---
Refers to: build/nuget/WinObjC.nuspec:5 in 08bff3a. [](commit_id = 08bff3ab1f2933749080aab51a25cf7cf3b9e1c9, deletion_comment = False)

**Comment by rajsesh-msft** [comment]
@bviglietta is this still needed?

**Pull request closed without merging**
