### PR TITLE
Adding macros to enhance return and failure checks.

### PR DESCRIPTION
**Pull request by msft-Jeyaram**
This is the commit into develop.

### CODE REVIEW

**Comment by msft-Jeyaram** [comment]
It will be one less merge and people (likes of brain) could use it if needed.

**Comment by DHowett-MSFT** [comment]
But it will be one more merge conflict when we resolve CGD2D, which touches the same files.

**Comment by msft-Jeyaram** [comment]
This was a direct cherry pick.

**Comment by msft-Jeyaram** [comment]
Verbal sign off from @DHowett-MSFT

**Pull request merged**
