### PR TITLE
Add __deprecated_msg macro

### PR DESCRIPTION
**Pull request by bviglietta**
Adding the __deprecated_msg macro, which exists on the reference platform.

### CODE REVIEW

**Comment by bviglietta** [comment]
@pradipd is added to the review. #Closed

**Comment by bbowman** [comment]
:shipit:

**Comment by pradipd** [comment]
The Codeflow CR doesn't have any files in it!
However, I looked on github and the change is fine.

**Comment by pradipd** [comment]
:shipit:

**Pull request merged**
