### PR TITLE
This change Implement UITextField tests following new functional test paradigm

### PR DESCRIPTION
**Pull request by yiyang-msft**
1. Implement UITextField functional tests using new functional test paradigm
2. Fixed a couple of issues found in the process
   1.) Background color was not binding correctly earlier
   2.) adding a const padding 16.0 represents textbox and its container control, 16 is the actual value through experiements.
   3.)In order for test to know about the dependency properties (#2607), I have to register the DP on frameworkElement, instead of TextField, similar to others. To void potential conflict, also rename it from Text to TextField_Text.
   4.)Per request, make UISlider tooltips disabled by default
   5.) Keep legacy UIText Field Test because it has some test for interactions which is still valuable.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/2706)

### CODE REVIEW

**Comment by nathpete-msft** [comment]
Review status: 0 of 16 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Frameworks/UIKit.Xaml/TextField.xaml.cpp, line 428 at r1](https://reviewable.io:443/reviews/microsoft/winobjc/2706#-KkHnjsn2ssKseR2RhhZ:-KkHnjsn2ssKseR2Rhh_:bb752ax) ([raw file](https://github.com/microsoft/winobjc/blob/64657e5df19fd875b02c8a2323571c847d37f384/Frameworks/UIKit.Xaml/TextField.xaml.cpp#L428)):*
> ```cpp
> }
> 
> void TextField::_SetBackgournd() {
> ```

Typo

---

*[Frameworks/UIKit.Xaml/TextField.xaml.h, line 246 at r1](https://reviewable.io:443/reviews/microsoft/winobjc/2706#-KkHo9otMDRFGpR-ixFk:-KkHo9otMDRFGpR-ixFl:bb752ax) ([raw file](https://github.com/microsoft/winobjc/blob/64657e5df19fd875b02c8a2323571c847d37f384/Frameworks/UIKit.Xaml/TextField.xaml.h#L246)):*
> ```objc
>     void _SetEnabled();
>     void _SetForeground();
>     void _SetBackgournd();
> ```

Typo

---

*[tests/functionaltests/UXTestHelpers.mm, line 230 at r1](https://reviewable.io:443/reviews/microsoft/winobjc/2706#-KkHqFPU1lGdHZp1Mmvq:-KkHqFPU1lGdHZp1Mmvr:b-6p43pj) ([raw file](https://github.com/microsoft/winobjc/blob/64657e5df19fd875b02c8a2323571c847d37f384/tests/functionaltests/UXTestHelpers.mm#L230)):*
> ```XML
> 
>     CGFloat r1, g1, b1, a1;
>     [col1 getRed:&r1 green:&g1 blue:&b1 alpha:&a1];
> ```

I don't think this works if supplied a UIColor that isn't in the RBG color space (ie. [UIColor grayColor]).

I handled this by extracting the CG color components and mapping them based on color space, here: https://github.com/Microsoft/WinObjC/pull/2608/files#diff-1ffe8a84e54a7ef5d70e87484bf501a7R163

---

*[tests/functionaltests/Tests/UIKitTests/UILabelTests.mm, line 471 at r1](https://reviewable.io:443/reviews/microsoft/winobjc/2706#-KkHsGDEGJXtk796cOLm:-KkHsGDEGJXtk796cOLn:b52dgm0) ([raw file](https://github.com/microsoft/winobjc/blob/64657e5df19fd875b02c8a2323571c847d37f384/tests/functionaltests/Tests/UIKitTests/UILabelTests.mm#L471)):*
> ```XML
>             auto colorBrush = textBlock.Foreground().as<Media::SolidColorBrush>();
>             ASSERT_TRUE(colorBrush);
>             EXPECT_TRUE(UXTestAPI::compareRGBAValues(UXTestAPI::ConvertWUColorToUIColor(colorBrush.Color()), label.textColor));
> ```

Any reason not to use the existing `UXTestAPI::IsRGBAEqual` for all of these checks? It already takes a `SolidColorBrush` and a `UIColor` as parameters to compare for you.

---

*[tests/functionaltests/Tests/UIKitTests/UITextFieldTests.mm, line 145 at r1](https://reviewable.io:443/reviews/microsoft/winobjc/2706#-KkHrL1Aepumn7LOB6KP:-KkHrL1Aepumn7LOB6KQ:bb752ax) ([raw file](https://github.com/microsoft/winobjc/blob/64657e5df19fd875b02c8a2323571c847d37f384/tests/functionaltests/Tests/UIKitTests/UITextFieldTests.mm#L145)):*
> ```XML
>             EXPECT_TRUE(textBox);
> 
>             textField.placeholder = @"placerholder";
> ```

Typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/winobjc/2706)*

**Comment by DHowett-MSFT** [comment]
@nathpete-msft I believe that `getRed:green:blue:alpha:` will do the colorspace conversion if necessary.

**Comment by nathpete-msft** [comment]
@DHowett-MSFT Yeah looks like you're right. I just tried it with `grayColor` and `whiteColor` and it does. I wasn't sure, since the docs say that it only handles conversion if it's in a compatible color space. I'm not sure what an incompatible color space would be as far as this method is concerned, or if this comment in the docs just happens to be outdated.

**Comment by nathpete-msft** [comment]
:shipit:

**Comment by nathpete-msft** [comment]
Reviewed 5 of 16 files at r1, 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/winobjc/2706)*

**Pull request merged**
