### PR TITLE
Update all certs for sample apps

### PR DESCRIPTION
**Pull request by pradipd**
Update all certs for sample apps.

### CODE REVIEW

**Comment by pradipd** [comment]
@rajsesh-msft is added to the review. #Closed

**Comment by DHowett-MSFT** [comment]
When you merge this, can you please make sure to change the commit message to note that these things got squashed together? Thanks!

**Comment by rajsesh-msft** [comment]
Did this help the CI build? It still appears broken.

**Comment by pradipd** [comment]
No. How do I recall/cancel this pull request?

---
In reply to: [254254289](https://github.com/Microsoft/WinObjC/pull/1158#issuecomment-254254289) [](ancestors = 254254289)

**Comment by pradipd** [comment]
I'll have a correct fix without the other changes in a 30 min's or so.

---
In reply to: [254265628](https://github.com/Microsoft/WinObjC/pull/1158#issuecomment-254265628) [](ancestors = 254265628,254254289)

**Comment by pradipd** [comment]
I'll clean this up and send a new CR.  
Please ignore this PR.

**Pull request closed without merging**
