### PR TITLE
Fix NSSet ObjectsPassingTest unit test

### LINKED ISSUE #767: NSSet.ObjectsPassingTest fails on OSX
[ RUN      ] NSSet.ObjectsPassingTest
Foundation/NSSetTests.mm:65: Failure
Value of: actual
  Actual: {(
    6,
    2
)}
Expected: expectedEvensLessThanFive
Which is: {(
    4,
    2
)}
[  FAILED  ] NSSet.ObjectsPassingTest (1 ms)

### PR DESCRIPTION
**Pull request by mnithish**
Fixes #767

### CODE REVIEW

**Comment by mnithish** [comment]
@ms-jihua is added to the review. #Closed

**Comment by DHowett-MSFT** [comment]
LOL.

**Comment by DHowett-MSFT** [comment]
Why did this work on our platform?

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by ms-jihua** [comment]
:shipit:

**Comment by ms-jihua** [comment]
Just guessing here:

Our platform happens to order the set in such a way that the test passes. The ref plat makes no such guarantee, so we hit the 6 early and stop.

---
In reply to: [237985558](https://github.com/Microsoft/WinObjC/pull/840#issuecomment-237985558) [](ancestors = 237985558)

**Comment by mnithish** [comment]
Correct - reference platform seems to store the value in BST so when we enumerate they seem to be give the value in the level order of how they were stored, so we hit 5 before we hit 2

---
In reply to: [237985796](https://github.com/Microsoft/WinObjC/pull/840#issuecomment-237985796) [](ancestors = 237985796,237985558)

**Pull request merged**
