### PR TITLE
Allow return of non-GDI-compatible family/subfamily names from CTFont…

### LINKED ISSUE #1758: Islandwood News crash when trying to insert nil font into dictionary

### PR DESCRIPTION
**Pull request by ms-jihua**
…Copy(Family)Name et al

Fixes #1758

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1778)

### CODE REVIEW

**Comment by msft-Jeyaram** [comment]
This was the root cause of #1751
Please close that with this.

**Comment by ms-jihua** [comment]
@msft-Jeyaram I'm confused what issue #1751 is actually describing - if it's describing an issue in NSLayoutManager with:
CTLineRef fitLine = static_cast<CTLineRef>(CFArrayGetValueAtIndex(CTFrameGetLines(frame.get()), 0));
then that issue still repros, and this was not the root cause (I may have also just opened a dupe at #1779)

**Comment by msft-Jeyaram** [comment]
@ms-jihua  I updated the bug #1751 .
This might not as well be related, but I have seen the crash upon attempting to obtain 
`static_cast(CFArrayGetValueAtIndex(CTFrameGetLines(frame.get()), 0));` and the frame is empty.

Are you able to repo as per #1751 steps?

**Comment by ms-jihua** [comment]
@msft-Jeyaram I am not able to repro the #1751 stack. I get #1758 on develop and #1779 after this change.

**Pull request merged**
