### PR TITLE
Fixing memory leak in NSTextStorage.

### LINKED ISSUE #490: _composed is not being released in NSTextStorage

### PR DESCRIPTION
**Pull request by Samanthi-Jeyaraj**
Fix #490

### CODE REVIEW

**Comment by rajsesh-msft** [comment]
@ms-jihua is added to the review. #Closed

**Comment by ms-jihua** [comment]
:shipit:

**Comment by bdrlamb** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
@Samanthi-Jeyaraj Thanks for your contribution.

**Pull request merged**
