### PR TITLE
Remove an internal header from drawing tests.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1469)

### CODE REVIEW

**Comment by ms-jihua** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
The build failed because the test actually _is_ relying on an internal feature. @msft-Jeyaram  :(

**Comment by DHowett-MSFT** [comment]
Abandoning PR.

**Comment by msft-Jeyaram** [comment]
The build failed since _CGContextDrawImageRectwas in CGContextInternal.h.
We still need that import (needs to be ifdefined for Mac testing)

**Pull request closed without merging**
