### PR TITLE
[ut] Clean resource stamps so resources get re-copied.

### LINKED ISSUE #1399: Foundation.UnitTests.exe broken on OSX
Probably related to recent makefile change. The following tests fail after a clean build, most likely related to not copying certain files (eg NSFileManagerUT.txt) to output directory.

[  FAILED  ] 14 tests, listed below:
[  FAILED  ] NSString.FromContentsOfURL
[  FAILED  ] NSString.FromContentOfFile
[  FAILED  ] NSURL.CheckResourceIsReachable
[  FAILED  ] NSURL.URLStrings
[  FAILED  ] NSURL.String
[  FAILED  ] NSBundle.Resources
[  FAILED  ] NSBundle.InfoPlist
[  FAILED  ] NSBundle.Localizations
[  FAILED  ] NSData.WriteToURLOptions
[  FAILED  ] NSDecimalNumber.Subtraction2
[  FAILED  ] NSFileManager.GetAttributes
[  FAILED  ] NSFileManager.EnumateDirectoryUsingURL
[  FAILED  ] NSPropertyList.Decode
[  FAILED  ] NSPropertyList.DecodeMutable

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Fixes #1399.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1400)

### CODE REVIEW

**Comment by aballway** [comment]
Does this resolve all test failures in #1399?

**Comment by DHowett-MSFT** [comment]
This resolves the path test failures. It doesn't solve the ones unrelated to missing resources.

**Comment by ms-jihua** [comment]
say what? do we know why the others are failing?

---
In reply to: [261049996](https://github.com/Microsoft/WinObjC/pull/1400#issuecomment-261049996) [](ancestors = 261049996)

**Comment by DHowett-MSFT** [comment]
@ms-jihua I have a different set of failing tests on my machine, possibly due to changes in 10.11 vs 10.10.

```
[  FAILED  ] NSURLSessionConfiguration.defaultSessionConfiguration
* SSL/TLS default version changed on 10.11

[  FAILED  ] NSURLSessionConfiguration.ephemeralSessionConfiguration
* SSL/TLS default version changed on 10.11

[  FAILED  ] NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier
* SSL/TLS default version changed on 10.11

[  FAILED  ] NSURL.URLStrings
2016-11-16 12:50:21.885 Foundation.UnitTests.exe[12839:790724] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFDictionary setObject:forKey:]: attempt to insert nil value (key: standardizedURL)'

[  FAILED  ] NSBundle.Paths
* It's looking for a Mac App Store receipt in the test bundle.

[  FAILED  ] NSDecimalNumber.Subtraction2
* Perhaps a legitimate failure.

[  FAILED  ] NSProcessInfo.NSProcessInfoGetProperties
NSProcessInfoTests.mm:60: Failure
Value of: processInfo.processName
  Actual: Foundation.UnitTests.exe
Expected: processName
Which is: Foundation.Unit
Process name should be equal
* What on earth?
```

**Comment by ms-jihua** [comment]
Interesting. Let's push this in for now and open bugs on the rest.

---
In reply to: [261067729](https://github.com/Microsoft/WinObjC/pull/1400#issuecomment-261067729) [](ancestors = 261067729)

**Comment by ms-jihua** [comment]
:shipit:

**Pull request merged**
