### PR TITLE
Updating all VS projects to target the RS1 SDK.

### PR DESCRIPTION
**Pull request by asimonov-msft**

### CODE REVIEW

**Comment by aballway** [comment]
Is this the change required for  #1048?

**Comment by DHowett-MSFT** [comment]
While we are here, can we bring up the `TargetPlatformVersionMin`?

**Comment by DHowett-MSFT** [comment]
Sorry, I mean to bring up min to `10586`.

**Comment by asimonov-msft** [comment]
@aballway No idea.

@DHowett-MSFT Our TargetPlatformVersionMin should already be at 10.0.10586.0. Is that not so?

**Comment by asimonov-msft** [comment]
Our WindowsTargetPlatformMinVersion should already be at 10.0.10586.0. Is that not so?

---
In reply to: [252996479](https://github.com/Microsoft/WinObjC/pull/1122#issuecomment-252996479) [](ancestors = 252996479)

**Comment by asimonov-msft** [comment]
No idea.

---
In reply to: [252994573](https://github.com/Microsoft/WinObjC/pull/1122#issuecomment-252994573) [](ancestors = 252994573)

**Comment by DHowett-MSFT** [comment]
Half our projects are at 10240 right now :)

---
In reply to: [253002438](https://github.com/Microsoft/WinObjC/pull/1122#issuecomment-253002438) [](ancestors = 253002438,252996479)

**Comment by bbowman** [comment]
Why do we want to update our min?

---
In reply to: [253003067](https://github.com/Microsoft/WinObjC/pull/1122#issuecomment-253003067) [](ancestors = 253003067,253002438,252996479)

**Comment by bbowman** [comment]
hmm got a little confused here but it is true that we use 10586 stuff and don't do a "fantastic" job of back compat so I approve.

---
In reply to: [253011472](https://github.com/Microsoft/WinObjC/pull/1122#issuecomment-253011472) [](ancestors = 253011472,253003067,253002438,252996479)

**Comment by bbowman** [comment]
(Does look like your build failed though so check that out)

---
In reply to: [253017160](https://github.com/Microsoft/WinObjC/pull/1122#issuecomment-253017160) [](ancestors = 253017160,253011472,253003067,253002438,252996479)

**Comment by bbowman** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by asimonov-msft** [comment]
The first round of builds failed because the server was missing the RS1 SDK. I fixed that.

---
In reply to: [253017271](https://github.com/Microsoft/WinObjC/pull/1122#issuecomment-253017271) [](ancestors = 253017271,253017160,253011472,253003067,253002438,252996479)

**Pull request merged**
