### PR TITLE
Fixed pre-defined NSValueTransformer constants.

### PR DESCRIPTION
**Pull request by triplef**
These match the reference implementation.

### CODE REVIEW

**Comment by rajsesh-msft** [comment]
Is there a reason you are using the actual values for the constants? The change doesn't hurt, but want to make sure you are not relying on the actual values instead of the constants defined in the headers.

**Comment by cloudmonkeypeng** [comment]
@rajsesh-msft    I have faced the same problem on the constants string  NSCalendarIdentifierGregorian / NSCalendarIndentifierChinese.  I'm not relying on the actual values. But in my opinion, when I want to output the constants string, it will be better if the actual values is same as the iOS.

**Comment by rajsesh-msft** [comment]
@cloudmonkeypeng Thanks! if you have a pull  request, will be happy to take it. :)

**Comment by triplef** [comment]
@rajsesh-msft thanks for the quick merge! We are using the actual values in XML documents for binding UI elements in our custom UI framework.

**Pull request merged**
