### PR TITLE
Fix libxml2.dll Windows Certification issue

### PR DESCRIPTION
**Pull request by timotiusmargo**
Define getcwd and getenv as null for MSVC 2015 to prevent restricted API calls that fail certification
Update libxml2 projects to point to the original icu folder that was renamed as iculegacy
Retarget libxml2 Windows 10 project to the latest Windows 10 SDK
Recompile and regenerate lib, dll, and pdb files
Update libxml2 build script

### CODE REVIEW

**Comment by rajsesh-msft** [comment]
Thank you for your contribution!

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Comment by Ramu-msft** [comment]
Fix is available in 0.1 Preview (November 12, 2015)

**Pull request merged**
