### PR TITLE
Fix test generate mode being always engaged due to a bad string compare.

### LINKED ISSUE #2027: [TAEF] Graphics Drawing tests show invalid results
the tests that should be failing shows up as passed.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Fixes #2027.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Oh no. I feared this would happen.

@aballway @MSFTFox Text drawing and Antialiasing tests are superexploding.

**Comment by bbowman** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
In CI buid again.

**Comment by DHowett-MSFT** [comment]
@msftfox let me know that the builds will fail (as evidenced by them failing :P)

**Comment by DHowett-MSFT** [comment]
This commit reduces the number of failing tests to 1.

**Comment by DHowett-MSFT** [comment]
@msft-Jeyaram Some of the rectangle clearing tests are failing.

000003_ cgclearrect transformed_0_greenline testimage cgcontext clearrect 0 0 100x100 0 9 0 4 -0 4 0 9 0 0 0 0
000012_ cgclearrect transformed_3_greenline testimage cgcontext clearrect 0 0 100x100 1 0 0 0 0 3 1 0 0 0 0 0

**Comment by DHowett-MSFT** [comment]
In CI build!

**Comment by DHowett-MSFT** [comment]
Hmm.

**Comment by DHowett-MSFT** [comment]
@msftfox the following test categories fail on the build machine:

```
TextAA_0_2_2_2
TextAA_1_1_0_0
TextAA_1_1_0_1
TextAA_1_1_0_2
TextAA_1_1_2_0
TextAA_1_1_2_1
TextAA_1_1_2_2
TextAA_1_2_2_2
TextAA_2_0_0_0
TextAA_2_0_0_1
TextAA_2_0_0_2
TextAA_2_0_1_0
TextAA_2_0_1_1
TextAA_2_0_1_2
TextAA_2_0_2_0
TextAA_2_0_2_1
TextAA_2_0_2_2
TextAA_2_1_0_0
TextAA_2_1_0_1
TextAA_2_1_0_2
TextAA_2_1_1_0
TextAA_2_1_1_1
TextAA_2_1_1_2
TextAA_2_1_2_0
TextAA_2_1_2_1
TextAA_2_1_2_2
TextAA_2_2_0_0
TextAA_2_2_0_1
TextAA_2_2_0_2
TextAA_2_2_1_0
TextAA_2_2_1_1
TextAA_2_2_1_2
TextAA_2_2_2_0
TextAA_2_2_2_1
TextAA_2_2_2_2
```

The "default" cases (2) are not unexpected, though they do represent true test failures. The non-default cases worry me.

We've known for some time that the build machines have different font rendering characteristics than our development machines, but we're not certain why. @aballway may have some insight.

**Pull request merged**
