### PR TITLE
Misc code clean-up to completely remove FreeType dependency in CoreText

### LINKED ISSUE #998: Reenable CTTypesetter Tests
Tests currently fail because of intermediate changes to Core Text.

### PR DESCRIPTION
**Pull request by mnithish**
Fixes #998 #1016

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
:shipit:

**Comment by ms-jihua** [comment]
> extern "C" {

(same in CTFontManager.mm)

---
In reply to: [248776359](https://github.com/Microsoft/WinObjC/pull/1024#issuecomment-248776359) [](ancestors = 248776359)

---
Refers to: Frameworks/CoreText/CTFont.mm:27 in ad4852d. [](commit_id = ad4852d11168bce7827e437c3ed8f4d8dd821864, deletion_comment = False)

**Comment by mnithish** [comment]
> extern "C" {

Thanks for catching that

---
In reply to: [248776670](https://github.com/Microsoft/WinObjC/pull/1024#issuecomment-248776670) [](ancestors = 248776670,248776359)

---
Refers to: Frameworks/CoreText/CTFont.mm:27 in ad4852d. [](commit_id = ad4852d11168bce7827e437c3ed8f4d8dd821864, deletion_comment = False)

**Comment by ms-jihua** [comment]
:shipit:

**Pull request merged**
