### PR TITLE
Objc2winmd binary update: Fix issues in projecting multipe types from async blocks

### PR DESCRIPTION
**Pull request by mukhole**

### CODE REVIEW

**Comment by pradipd** [comment]
:shipit:

**Comment by ms-jihua** [comment]
Seeing an issue when building FunctionalTests after pulling this:

LNK1104	cannot open file 'ObjCUWP_Windows_Media_Core_Protection_Playback_Capture_Devices.lib'

The lib checked in is named 'ObjCUWP_Windows_Media_Playback_Protection_Core_Capture_Devices.lib' instead of the above ordering of namespaces - was there a misnaming somewhere?

**Comment by DHowett-MSFT** [comment]
@ms-jihua You may have an old `.obj` laying around; clean the offending project and it should work :smile:

**Comment by ms-jihua** [comment]
@DHowett-MSFT Yup, that fixed it. Sorry for the trouble!

**Pull request merged**
