### PR TITLE
Fix extra retain of CTTypesetter

### LINKED ISSUE #1754: Leak in CTFramesetterCreateWithAttributedString due to assignment (vs. attach) of ret->_typesetter
This code leaks:

```
CTFramesetterRef CTFramesetterCreateWithAttributedString(CFAttributedStringRef string) {
    _CTFramesetter* ret = [_CTFramesetter alloc];
    ret->_typesetter = static_cast<_CTTypesetter*>(CTTypesetterCreateWithAttributedString(string));
    return static_cast<CTFramesetterRef>(ret);
}
```

Which causes runtime leaks when calculating font sizes in UIKit; for example:

Identifier	Count	Size (Bytes)	Count Diff.	Size Diff (Bytes)	Module	
 - -[UILabel intrinsicContentSize]	14	352	+14	+352	UIKIT.DLL
   - -[NSString(UIKitAdditions) sizeWithFont:]	14	352	+14	+352	UIKIT.DLL
     - -[NSString(UIKitAdditions) sizeWithFont:constrainedToSize:]	14	352	+14	+352	UIKIT.DLL
       - -[NSString(UIKitAdditions) _sizeWithAttributes:constrainedToSize:]	14	352	+14	+352	UIKIT.DLL
         - -[NSAttributedStringPrototype initWithString:attributes:]	12	320	+12	+320	FOUNDATION.DLL
           - CFAttributedStringCreate	12	320	+12	+320	COREFOUNDATION.DLL
             + CFDictionaryCreateMutableCopy	6	176	+6	+176	COREFOUNDATION.DLL
             + CFRunArrayCreate	4	112	+4	+112	COREFOUNDATION.DLL
             - _CFRuntimeCreateInstance	2	32	+2	+32	COREFOUNDATION.DLL
               - CFAllocatorAllocate	2	32	+2	+32	COREFOUNDATION.DLL
                 - __CFAllocatorSystemAllocate	2	32	+2	+32	COREFOUNDATION.DLL
                     [External Code]	2	32	+2	+32	[External Code]
         - CTFramesetterCreateWithAttributedString	2	32	+2	+32	CORETEXT.DLL
           - CTTypesetterCreateWithAttributedString	2	32	+2	+32	CORETEXT.DLL
             - +[NSObject alloc]	2	32	+2	+32	FOUNDATION.DLL
               - +[NSObject allocWithZone:]	2	32	+2	+32	FOUNDATION.DLL
                 - class_createInstance	2	32	+2	+32	LIBOBJC2.DLL
                   - allocate_class	2	32	+2	+32	LIBOBJC2.DLL
                       [External Code]	2	32	+2	+32	[External Code]

We should fix this and scrub the rest of the codebase for similar issues.

### PR DESCRIPTION
**Pull request by aballway**
Fixes #1754

This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1756)

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Anything else like this in the code?

**Comment by DHowett-MSFT** [comment]
The CT code, that is.

**Comment by aballway** [comment]
There doesn't seem to be.  I cleaned up a lot of memory leaks in CT a while back, I think this is the only one I missed/created since.

**Comment by MSFTFox** [comment]
:shipit:

**Pull request merged**
