### PR TITLE
Do not re-create text views on every text draw in CTCatalog test app

### LINKED ISSUE #1046: CTCatalog testapp is re-creating text views on every text draw causing the view to flicker
The bad flicker in the test app when we slide the slider to change fonts is due to this. We seem to be deleting and re-creating text views on every text draw call.

### PR DESCRIPTION
**Pull request by mnithish**
Fixes #1046

### CODE REVIEW

**Comment by mnithish** [comment]
@aballway is added to the review. #Closed

**Comment by rajsesh-msft** [comment]
:shipit:

**Comment by ms-jihua** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
:shipit:

**Comment by aballway** [comment]
:shipit:

**Comment by aballway** [comment]
Wouldn't you know there's a better way of updating views than murdering and replacing them

**Pull request merged**
