### PR TITLE
Reintroduce the ~150 (!) binaries that were not under Git-LFS

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Wow.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
@oliversa-msft is added to the review. #Closed

**Comment by DHowett-MSFT** [comment]
@mnithish is added to the review. #Closed

**Comment by DHowett-MSFT** [comment]
@rajsesh-msft is added to the review. #Closed

**Comment by mnithish** [comment]
:shipit:

**Comment by oliversa-msft** [comment]
:shipit:

**Comment by MSFTFox** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
Due to LFS's frailty, I will merge this manually when the build passes.

**Pull request merged**
