### PR TITLE
[CGD2D] Merge develop from 20170125.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
@ms-jihua This includes a resolution for the #1705 and #1750 conflicts.

@aballway This includes a resolution for the #1692 conflict.

```
    Conflicts:
            Frameworks/CoreGraphics/CGContext.mm
            Frameworks/include/CGContextInternal.h
            build/CoreGraphics/dll/CoreGraphics.def
            tests/unittests/CoreGraphics.drawing/ImageComparison.cpp
```

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Sorry @aballway, I meant "for the #1723 conflict."

**Comment by DHowett-MSFT** [comment]
Sorry @aballway, I actually really meant "the #1780 conflict". Why do you have so many issues with the same name?

**Comment by msft-Jeyaram** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
@henryfox The release build suffered an image failure:

### `CGPath.PathApplyDraw` image

testimage cgpath pathapplydraw

### `CGPath.PathApplyDraw` Greenline
greenline testimage cgpath pathapplydraw

**Pull request merged**
