### PR TITLE
Upgrade build.sln projects to VS 2017 and toolset v141

### PR DESCRIPTION
**Pull request by memontic-ms**
Hopefully this will avoid any trouble with VS 2017 installs finding the v140 toolset.

### CODE REVIEW

**Comment by bviglietta** [comment]
:shipit:

**Comment by bbowman** [comment]
:shipit:

**Comment by memontic-ms** [comment]
Okay, *now* all of build.sln should be using platform toolset v141.

**Comment by memontic-ms** [comment]
This PR partially resolves #2206

**Pull request merged**
