### PR TITLE
ObjC2Winmd binary update: 

### PR DESCRIPTION
**Pull request by mukhole**
Added support for containers with heterogeneous types

### CODE REVIEW

**Comment by pradipd** [comment]
:shipit:

**Comment by pradipd** [comment]
What caused the projections binaries to be updated?

**Comment by pradipd** [comment]
nevermind.

---
In reply to: [281839514](https://github.com/Microsoft/WinObjC/pull/2035#issuecomment-281839514) [](ancestors = 281839514)

**Comment by mukhole** [comment]
I changed the header RTHelpers.h which is used by all the projection binaries.

**Pull request merged**
