### PR TITLE
Fix _even more_ instances where we used nil instead of nullptr

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
(this is ridiculous!)

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/2851)

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
The builds have passed, but they could not be reported.

**Comment by DHowett-MSFT** [comment]
image

**Review by jjeyaraj — APPROVED** [review]

**Comment by DHowett-MSFT** [comment]
@jjeyaraj :heart: you're awesome, thank you

**Comment by DHowett-MSFT** [comment]
Turns out there were _even even more!_

**Review by MSFTFox — APPROVED** [review]

**Pull request merged**
