### PR TITLE
Modifying mdmerge to include UniversalAPIContract.winmd

### PR DESCRIPTION
**Pull request by pradipd**

### CODE REVIEW

**Comment by pradipd** [comment]
@mukhole is added to the review. #Closed

**Comment by pradipd** [comment]
@artems is added to the review. #Closed

**Comment by rajsesh-msft** [comment]
Should objc2winmd.exe be in lfs?

**Comment by pradipd** [comment]
It is.

---
In reply to: [253648558](https://github.com/Microsoft/WinObjC/pull/1146#issuecomment-253648558) [](ancestors = 253648558)

**Comment by pradipd** [comment]
Err. It's in lfs because it's a binary.  Aren't all binaries in lfs?

---
In reply to: [253648659](https://github.com/Microsoft/WinObjC/pull/1146#issuecomment-253648659) [](ancestors = 253648659,253648558)

**Comment by rajsesh-msft** [comment]
My bad, codeflow shows it as a binary, for some reason, i expected to see the lfs changes, that only is seen in gitk.  

---
In reply to: [253648923](https://github.com/Microsoft/WinObjC/pull/1146#issuecomment-253648923) [](ancestors = 253648923,253648659,253648558)

**Comment by pradipd** [comment]
@asimonov-msft is added to the review. #Closed

**Comment by mukhole** [comment]
:shipit:

**Pull request closed without merging**
