### PR TITLE
WinObjC.Build and WinObjC.Tools packages

### PR DESCRIPTION
**Pull request by bbowman**
WinObjC.Build and WinObjC.Tools packages
Description:
This change reorganizes the repo into more isolated components. Namely it
introduces the WinObjC.Build folder which contains a new .sln responsible
for building the set of "build support" tooling in two new packages.

WinObjC.Build - "in build" tooling
  - Clang
  - clang consumption .props and .targets
  - commandline style tools used in build like depends, xib2nib, etc

WinObjC.Tools - "out of build" tooling. Delivered and installed as a Chocolately package.
  - VSIX
  - vsimporter
  - Nugetizer vsix

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1405)

### CODE REVIEW

**Comment by bbowman** [comment]
This 100% *WILL* break the build right now. I still need to get WinObjC.Frameworks added and integrated before we have any hope of a final build working. This change is already massive though so I wanted to get a first thing into a new long running branch (packaging) before anything else too crazy gets lumped on.

**Comment by rajsesh-msft** [comment]
> #ifndef __WOCSTDLIB_COMINCLUDES

I dont understand why these includes are now under the winobjc.build folder.  

---
Refers to: WinObjC.Build/include/WOCStdLib/COMIncludes.h:17 in 87d9c61. [](commit_id = 87d9c61f42993e63975a076c081242de2b00d854, deletion_comment = False)

**Comment by bbowman** [comment]
I probably *DONT* want to check in the contents of .tools. Right now running .\init.cmd or .\init.ps1 will add those items. Need to re-read 
[https://www.visualstudio.com/en-us/docs/package/nuget/bootstrap-nuget](https://www.visualstudio.com/en-us/docs/package/nuget/bootstrap-nuget)

**Comment by memontic-ms** [comment]
What about the remainder of the original contents of WinObjC/bin that did not make it into WinObjC.Build/bin?

**Comment by bbowman** [comment]
what are those things?

---
In reply to: [261120037](https://github.com/Microsoft/WinObjC/pull/1405#issuecomment-261120037) [](ancestors = 261120037)

**Comment by bbowman** [comment]
ClangCompileTask items shouldn't be there in the root of the repo.

**Comment by bbowman** [comment]
If there is something missing from the actual contents of a produced package yes but I think I got them all. Things like acbuilder etc that appear to just be deleted are usually a project added to packager. Let me know if something is gone gone though.

---
In reply to: [261123970](https://github.com/Microsoft/WinObjC/pull/1405#issuecomment-261123970) [](ancestors = 261123970,261120037)

**Comment by memontic-ms** [comment]
So we won't have a version of acbuilder.exe, Xib2Nib.exe, etc, checked in anywhere? Or will we also be checking in the final package to WinObjC/WinObjC.Build/?

---
In reply to: [261125604](https://github.com/Microsoft/WinObjC/pull/1405#issuecomment-261125604) [](ancestors = 261125604,261123970,261120037)

**Comment by pradipd** [comment]
> 2. Build WinObjC/tools/tools.sln

Is this file in the correct place?

---
Refers to: WinObjC.Build/README.md:8 in 1072d65. [](commit_id = 1072d6595571d4eea1794a1d0b9c0edba79d33d5, deletion_comment = False)

**Comment by pradipd** [comment]
> 2. Build WinObjC/tools/tools.sln

Seems like it should be in winobjc.tools

---
In reply to: [261327236](https://github.com/Microsoft/WinObjC/pull/1405#issuecomment-261327236) [](ancestors = 261327236)

---
Refers to: tools/README.md:8 in 1072d65. [](commit_id = 1072d6595571d4eea1794a1d0b9c0edba79d33d5, deletion_comment = False)

**Comment by pradipd** [comment]
> 

What is a pkgdef file?

---
Refers to: WinObjC.Build/bin/VC_Pkg_Core_Registration_ObjC.pkgdef:4 in 1072d65. [](commit_id = 1072d6595571d4eea1794a1d0b9c0edba79d33d5, deletion_comment = False)

**Comment by bbowman** [comment]
correct. I am trying desperately to reduce the number of checked in binaries we have. We will *not* be checking in final packages either. 

---
In reply to: [261129683](https://github.com/Microsoft/WinObjC/pull/1405#issuecomment-261129683) [](ancestors = 261129683,261125604,261123970,261120037)

**Comment by bbowman** [comment]
> 

no clue! Its something leonard added in the long ago for supporting .mm .m file automagic handling?

---
In reply to: [261328280](https://github.com/Microsoft/WinObjC/pull/1405#issuecomment-261328280) [](ancestors = 261328280)

---
Refers to: WinObjC.Build/bin/VC_Pkg_Core_Registration_ObjC.pkgdef:4 in 1072d65. [](commit_id = 1072d6595571d4eea1794a1d0b9c0edba79d33d5, deletion_comment = False)

**Comment by bbowman** [comment]
> 

its possible this needs to go with the vsix not with the clang.dll

---
In reply to: [261336287](https://github.com/Microsoft/WinObjC/pull/1405#issuecomment-261336287) [](ancestors = 261336287,261328280)

---
Refers to: WinObjC.Build/bin/VC_Pkg_Core_Registration_ObjC.pkgdef:4 in 1072d65. [](commit_id = 1072d6595571d4eea1794a1d0b9c0edba79d33d5, deletion_comment = False)

**Pull request closed without merging**
