### PR TITLE
Merge develop into CGD2D.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Conflicts resolved: CGContext, CGFont, CALayer, CoreFoundationLib.vcxproj, CoreFoundation.def.

Changes from develop:
* Removed SetScaleFactor (Context, CALayer).
* Added lineAscent argument to CGContextDrawGlyphRun.
* We had changes in CGFontDrawGlyphsAtPoint, which was removed.

***Requires manual merging; do not squash, rebase or merge.***

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1242)

### CODE REVIEW

**Comment by msft-Jeyaram** [comment]
:shipit:

**Comment by rajsesh-msft** [comment]
:shipit:

**Comment by aballway** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
@msftfox There are some issues in the use of CGPath internal functions. Can you please branch off this granch (Microsoft/WinObjC@3496ce9), CR a pull request into this branch, and we can merge both?

**Comment by DHowett-MSFT** [comment]
Running new CI build.

**Pull request merged**
