### PR TITLE
Move RTHelpers.h to WinObjC repo

### PR DESCRIPTION
**Pull request by mukhole**
RTHelpers.h needs to be moved to WinObjC repo so that it is publicly available.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1229)

### CODE REVIEW

**Comment by pradipd** [comment]
I only see ARM binaries.

**Comment by pradipd** [comment]
And I don't see RTObjcInterop.dll

---
In reply to: [256468943](https://github.com/Microsoft/WinObjC/pull/1229#issuecomment-256468943) [](ancestors = 256468943)

**Comment by mukhole** [comment]
Some problem with github, I can see them in gitk.
Looks like there is a limit to the number of files which can be sent out for review :)

---
In reply to: [256469086](https://github.com/Microsoft/WinObjC/pull/1229#issuecomment-256469086) [](ancestors = 256469086,256468943)

**Comment by pradipd** [comment]
Apparently, github doesn't scale all that well.  We confirmed using gitk all the projections binaries were changed.

---
In reply to: [256469086](https://github.com/Microsoft/WinObjC/pull/1229#issuecomment-256469086) [](ancestors = 256469086,256468943)

**Comment by pradipd** [comment]
:shipit:

**Comment by asimonov-msft** [comment]
:shipit:

**Pull request merged**
