### PR TITLE
[CGD2D] Merge develop from 2016-11-10.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Conflicts:
        Frameworks/CoreGraphics/CGBitmapImage.mm
        Frameworks/CoreGraphics/CGContext.mm
        Frameworks/QuartzCore/CALayer.mm
        Frameworks/UIKit/StarboardXaml/CompositorInterface.mm
        Frameworks/include/CGIWICBitmap.h

Changes required:
* CGBitmapImage has been removed entirely.
* Surface Format has been dropped from CGBitmapContext and CGIWICBitmap, as the render target is controlled elsewhere.
* Compositor had a conflict in the `#include` lines.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1354)

### CODE REVIEW

**Comment by aballway** [comment]
:shipit:

**Comment by ms-jihua** [comment]
Frameworks/include/CGIWICBitmap.h was called out as a conflict but I don't see it in the diff?

**Comment by DHowett-MSFT** [comment]
I do not believe it changed after conflict resolution.

**Comment by DHowett-MSFT** [comment]
Please hold off on this review: it requires another merge to build.

**Comment by DHowett-MSFT** [comment]
Okay, this is safe for more review. :P

**Pull request merged**
