### PR TITLE
UINavigationBar should retain _curItem and _newItem UINavigationItem instances (fix crash on UINavigationBar dealloc)

### PR DESCRIPTION
**Pull request by ehren**

### CODE REVIEW

**Comment by Ramu-msft** [comment]
@bdrlamb is added to the review. #Closed

**Comment by yiyang-msft** [comment]
:+1:

**Comment by DHowett-MSFT** [comment]
>     _newItem = nil;

since you switched to idretain, we can remove this for cur/new

---
Refers to: Frameworks/UIKit/UINavigationBar.mm:577 in 0902644. [](commit_id = 0902644a6f40cdab45d87df39701e4db06726a60, deletion_comment = False)

**Comment by DHowett-MSFT** [comment]
:+1:

**Comment by ehren** [comment]
should the others like _leftButton go too?

**Comment by msft-Jeyaram** [comment]
Yep, all of the variables wrapped in idretain do not need to be set to nil in dealloc.

**Comment by ehren** [comment]
added removal of the rest of them (decided not to add unsetting of the delegate though)

**Pull request merged**
