### PR TITLE
Adding SQLite3 headers and libs to SDK

### PR DESCRIPTION
**Pull request by asimonov-msft**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/winobjc/1086)

### CODE REVIEW

**Comment by rajsesh-msft** [comment]
Why? There is the sqllite uwp library that developers should install and use. It allows them to use the version they want without waiting for WINOBJC to bundle it.

**Comment by rajsesh-msft** [comment]
:clock:

**Comment by rajsesh-msft** [comment]
:clock1:

**Comment by bbowman** [comment]
Agreed. This also doesn't appear to valuable for any modules we provide internally so it doesn't really make sense what this review is trying to accomplish. Lets discuss offline and figure out the correct approach.

---
In reply to: [251723177](https://github.com/Microsoft/WinObjC/pull/1086#issuecomment-251723177) [](ancestors = 251723177)

**Comment by bbowman** [comment]
:clock1:

**Comment by rajsesh-msft** [comment]
Closing this pull request based on internal discussions.

**Pull request closed without merging**
