### PR TITLE
Clang format and configuration for code style

### PR DESCRIPTION
**Pull request by vmagaziy**
This **PL** contains initial preparations discussed in Issue #54 (_Define a code style to follow for all sources_):
* Initial version of Python pre-commit hook, so it requires having Python installed
* Scripts for installation the hook
* **clang-format** binaries v3.6.2 for Windows and OS X
* Configuration for **clang-format** based on [Google Code Style] (http://google.github.io/styleguide/objcguide.xml)

This setup has been tested on OS X and Windows only and in order to have it work properly on Windows it has to checkout sources with LF endings (another word it has to have `git config --global core.autocrlf false` executed before the checkout).

Please note, PowerShell environment is supposed to used for running Git, so all suggestions are provided assuming such commands as `cat` and `patch` are supported, please see example below:

```
C:\Users\USER\Documents\GitHub\WinObjC [clang_format_and_configuration_for_code_style +0 ~1 -0]> git diff
diff --git a/Frameworks/Foundation/NSArray.mm b/Frameworks/Foundation/NSArray.mm
index 061b13c..d3fb9aa 100644
--- a/Frameworks/Foundation/NSArray.mm
+++ b/Frameworks/Foundation/NSArray.mm
@@ -33,7 +33,7 @@ __declspec(dllimport) extern "C" int CFNSBlockCompare(id obj1, id obj2, void *bl
 @class NSXMLPropertyList, NSPropertyListReader, NSArrayConcrete, NSMutableArrayConcrete, NSPropertyListWriter_Binary;

 @implementation NSArray : NSObject
-    +(NSArray*) arrayWithObjects:(NSObject*)first , ...{
+    +(             NSArray                *) arrayWithObjects:(           NSObject * )first , ...{
         va_list pReader; va_start(pReader, first);
         NSArray* ret = [self new];
         if ( first == nil ) return [ret autorelease];
C:\Users\USER\Documents\GitHub\WinObjC [clang_format_and_configuration_for_code_style +0 ~1 -0]> git commit -a
ERROR: INCORRECT CODE STYLE
If you believe it is correct, use '-n' or '--no-verify' option to ignore this error.
Otherwise execute 'cat c:\users\user\appdata\local\temp\com.microsoft.WinObjC.codestyle.jeovzb.patch | patch -p0' to fix found issues.
Do NOT forget to add changes to the index if needed or use '-a' option, otherwise they will be lost.
--- Frameworks/Foundation/NSArray.mm    (before formatting)
+++ Frameworks/Foundation/NSArray.mm    (after formatting)
@@ -30,13 +30,15 @@

 __declspec(dllimport) extern "C" int CFNSBlockCompare(id obj1, id obj2, void *block);

-@class NSXMLPropertyList, NSPropertyListReader, NSArrayConcrete, NSMutableArrayConcrete, NSPropertyListWriter_Binary;
+@class NSXMLPropertyList, NSPropertyListReader, NSArrayConcrete,
+    NSMutableArrayConcrete, NSPropertyListWriter_Binary;

 @implementation NSArray : NSObject
-    +(             NSArray                *) arrayWithObjects:(           NSObject * )first , ...{
-        va_list pReader; va_start(pReader, first);
-        NSArray* ret = [self new];
-        if ( first == nil ) return [ret autorelease];
++ (NSArray *)arrayWithObjects:(NSObject *)first, ... {
+  va_list pReader;
+  va_start(pReader, first);
+  NSArray *ret = [self new];
+  if (first == nil) return [ret autorelease];
         CFArrayAppendValue((CFMutableArrayRef) ret, (const void *) first);

         id curVal = va_arg(pReader, id);

```

### CODE REVIEW

**Comment by asimonov-msft** [comment]
@vmagaziy Checking out sources with LF line endings under Windows may be an issue. This has caused us serious problems in the past, so now we use `core.autocrlf true`. In particular, git would occasionally become confused about the mixed line endings in modified files, and would consider all contents of the file to be changed.

**Comment by vmagaziy** [comment]
I don't have any experience of using Git under Windows, but I believe it
may only be the case when the user editor does not appreciate original line
endings.

**Comment by vmagaziy** [comment]
@asimonov-msft , if resetting the `autocrlf` flag is not an option, I will try to rework the solution to appreciate CRLF line endings for Windows.

**Comment by vmagaziy** [comment]
@asimonov-msft, please review this **PL** with fixes.

**Comment by s5msft** [comment]
@vmagaziy we love this suggestion, and we have a tool to accomplish (essentially) this same task coming in the very near future

**Comment by vmagaziy** [comment]
@s5msft, thanks but this just kills all my initiative to contribute to this project.  If you've got something happening under the hood, please make it public, so it becomes visible to the community and we don't have to reinvent the wheel.  I would be also great if you define a set of tasks and priorities which can be taken by the community to avoid duplications like this one.

**Comment by jmsaunders-ms** [comment]
Hi @vmagaziy, I've been working on this a little bit. The reason why we don't want to accept your commit is that we have a lot of reservations about having a dependency on Python. I'm also not a huge fan of pre-commit hooks in general but emitting a patch is IMO not a great solution.

I've ported the important bits of the script to C#, which will instead function on the working version of the diffs (rather than staged). The plan is to show a diff which the user can accept or deny.

This work started after your pull request. We're happy with the broad strokes of what you want to do and I apologize for not making this explicit earlier.

**Comment by vmagaziy** [comment]
@jmsaunders-ms, Thanks for your message and sharing the ideas. My initial thought was that Python could be used for both Windows and Mac and other platforms, but if the hook/verification tool is a native application it automatically means it's for Windows only. For instance, I wanted to contribute to implementation of Foundation and other non UI frameworks as well as create unit tests by running them on OS X (see #59 for details) and in that case it will be really helpful, as well as if someone running Linux may decide to tweak some implementation. But I 100% agree that having an additional dependency on Python is a bad thing -- on OS X, Python is pre-bundled which is not the case on Windows. AFAIK, it's now possible to run C# code on different platforms, so can you please provide binaries of your tool for different platforms once it's ready?

**Comment by vmagaziy** [comment]
@jmsaunders-ms, having this tool executed by an intention is an error prone approach in my opinion, since authors of PLs may forget to use it while committing/pushing changes. For sure, if you're planning to create a script for submitting changes like in `git cl upload` used in *Chromium*, then this tool can be integrated and it becomes impossible to forget to execute it.

**Comment by jmsaunders-ms** [comment]
Sorry - this is taking longer than I expected and I wanted to give some updates.

Clang-format has had some issues with our source base and we've had trouble with a couple things:
1. The preceding whitespace (and comments) on method definitions causes clang-format to severely break methods following empty methods. This is fixable with a quick sed prior to running the tool, but that is not always an effect-free process (multiline strings).
2. Laying out c-style struct initializers does not work great for us (especially with the C++11 option on, sadly). We would like to preserve some formatting of them (matrices, setting up some function pointer tables, etc). None of the options (I have seen) support behaviour that satisfies our needs.
3. The regular bike-shedding on choosing a coding style. :)

Right now I'm strongly considering running a pass over the code base once, cleaning up stuff I disagree with and pushing and then spending idle cycles trying to make clang-format work better for our purposes. Until then a commit hook to reject pull requests that don't match the style is untenable.

**Pull request closed without merging**
