### PR TITLE
[Foundation Dependency Removal] Should use use CoreFoundation vs Foundation: Strings should be created via CFSTR vs NS

### PR DESCRIPTION
**Pull request by msft-Jeyaram**
#2352

### CODE REVIEW

**Comment by aballway** [comment]
> #import "_CGLifetimeBridgingType.h"

Should this go as well?

---
Refers to: Frameworks/CoreGraphics/CGColorSpace.mm:25 in 19da71a. [](commit_id = 19da71a769bc7fdcd5db7b38ca18efcb24d3d4d8, deletion_comment = False)

**Comment by ms-jihua** [comment]
Is there broader scoped context to this change? (Are we looking to remove enough dependencies that we can make some sort of build change, or are we just removing dependencies for code quality's sake?)

**Comment by msft-Jeyaram** [comment]
@aballway  yes yes yes
@ms-jihua  this is a small part of the grand plan of completely removing Foundation/UIKit dependencies from CoreText and CoreGraphics

**Comment by msft-Jeyaram** [comment]
There are few more instances, updating CR.

**Pull request merged**
