### PR TITLE
Fix various leaks in Foundation

### PR DESCRIPTION
**Pull request by ehren**

### CODE REVIEW

**Comment by ehren** [comment]
No prob (kinda fun!)

**Comment by jaredhms** [comment]
:shipit:

**Comment by DHowett-MSFT** [comment]
In CI build.

**Comment by jaredhms** [comment]
Thanks for the fixes!  Changes in CI build.

**Comment by DHowett-MSFT** [comment]
The release build appeared to fail for an unrelated reason (possibly #1702); restarting it.

**Comment by DHowett-MSFT** [comment]
Thanks!

**Comment by pradipd** [comment]
Ehren,
First thanks again for this commit.  We really appreciate the memory leak fixes.

However, we had to revert this because the change in NSThread.mm L359 was causing the functional tests (CancelPreviousPerformRequestsWithTarget) to fail.

A prior test allocates the currentThread object and assigns it to thread local storage (pthread_setspecific(tlsNSThread, reinterpret_cast<void*>(self)); L205).  
STARBOARD.DLL!pthread_setspecific
FOUNDATION.DLL!-[NSThread _associateWithCurrentThread]
FOUNDATION.DLL!+[NSThread currentThread]
FOUNDATION.DLL!+[NSRunLoop currentRunLoop]
Foundation.UnitTests.exe!NSObject_PerformSelectorAfterDelaySanity_Test::TestBody


Once the test finishes the autorelease pool is drained, and TLS is left holding a pointer to a released object.

Then, CancelPreviousPerformRequestsWithTarget runs, and eventually tries to use the released object that is stored in TLS
STARBOARD.DLL!pthread_getspecific
FOUNDATION.DLL!+[NSThread _threadObjectFromCurrentThread]
FOUNDATION.DLL!+[NSThread currentThread]
FOUNDATION.DLL!+[NSRunLoop currentRunLoop]
Foundation.UnitTests.exe!NSObject_CancelPreviousPerformRequestsWithTarget_Test::TestBody

**Comment by ehren** [comment]
@pradipd, that's not a problem. Glad it wasn't the NSObject_CancelPreviousPerformRequestsWithTarget implemetation itself!

I can submit a new commit not including the NSThread change (though there's no rush getting that in - I'll wait until after an NSThread/NSRunloop fix is determined). I wouldn't mind taking a look at the underlying memory management issue for curiosities sake but anyone that wants to look at this today should go ahead (won't have time today).

**Pull request merged**
