### PR TITLE
Disabling windows specific test on OSX

### PR DESCRIPTION
**Pull request by msft-Jeyaram**
#1724

### CODE REVIEW

**Comment by bbowman** [comment]
FOO_DISABLED_TEST is supposed to indicate that tests are *temporarily* disabled and will be fixed pending some change. We already have a windows only test binary for foundation for tests that are truly windows specific in their operation. Let's not muddy the waters here...

**Comment by ms-jihua** [comment]
+1 to what @bbowman said (it totally slipped my mind)

**Comment by DHowett-MSFT** [comment]
When you commit this, _please_ reword the commit to actually say what changed.

**Comment by msft-Jeyaram** [comment]
@ping some movements please take a look

**Comment by bbowman** [comment]
:shipit:

**Pull request merged**
